language: python
python:
  - 3.6
#install:
#  - pip install python3-dev pybind11
script:
  - python3 ./python/try.py
  - python3 ./mix/treetest.py
  - source python_build.sh
  - python3 ./python/exam_tests.py