language: python
python:
  - 3.6
#install:
#  - pip install python3-dev pybind11
script:
#  - source make.sh
  - cd ./mix
  - make
  - python3 ./mix/treetest.py
  - cd ./../python
  - python3 ./python/exam_tests.py