language: python
python:
  - 3.6
#install:
#  - pip install python3-dev pybind11
script:
#  - source make.sh
  - cd ./c++
  - make
  - python3 ./treetest.py
  - cd ./../python
  - python3 ./exam_tests.py