
before_install:
  - sudo apt-get install python3-dev 

language: python
python:
  - 3.6
#install:
  - pip install -r requirements.txt
#  - pip install python3-dev pybind11
script:
  - python3 ./mix/treetest.py
  - python3 ./python/PostcardList.py
  - python3 ./mix/examplePybind11/pythonExample.py
  - python3 ./pythonExample.py	
